# Generated by Django 5.0.6 on 2024-07-01 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('second_name', models.CharField(blank=True, max_length=100)),
                ('third_name', models.CharField(blank=True, max_length=100)),
                ('snils', models.CharField(blank=True, max_length=11)),
                ('is_auth', models.BooleanField(default=False)),
                ('course', models.CharField(blank=True, choices=[('1', 'Первый курс'), ('2', 'Второй курс'), ('3', 'Третий курс'), ('4', 'Четвертый курс'), ('5', 'Пятый курс'), ('6', 'Шестой курс')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='StudentRaw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('second_name', models.CharField(max_length=100)),
                ('third_name', models.CharField(max_length=100)),
                ('snils', models.CharField(max_length=11)),
            ],
        ),
    ]
