# Generated by Django 4.2.13 on 2024-07-07 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_botuser_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botuser',
            name='course',
            field=models.CharField(choices=[('1', 'Первый курс'), ('2', 'Второй курс'), ('3', 'Третий курс'), ('4', 'Четвертый курс'), ('5', 'Пятый курс'), ('6', 'Шестой курс')], max_length=1),
        ),
    ]
