# Generated by Django 4.2.13 on 2024-07-07 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_botuser_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='botuser',
            old_name='snils',
            new_name='auth_number',
        ),
        migrations.RenameField(
            model_name='studentraw',
            old_name='snils',
            new_name='auth_number',
        ),
    ]
