version: '3'

services:
  db:
    image: postgres
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - db-data:/var/lib/postgresql/data

  django:
    build: .
    env_file:
      - .env
    ports:
      - "8000:8000"
    command: [ "/rsmu_bot/docker/app.sh" ]
    volumes:
      - ./rsmu_bot/static:/rsmu_bot/rsmu_bot/static
      - ./rsmu_bot/media:/rsmu_bot/rsmu_bot/media
    depends_on:
      - db

  bot:
    build: .
    env_file:
      - .env
    volumes:
      - ./rsmu_bot/static:/rsmu_bot/rsmu_bot/static
      - ./rsmu_bot/media:/rsmu_bot/rsmu_bot/media
    depends_on:
      - django
    command: python manage.py run_bot

  check_polls:
    stdin_open: true
    build: .
    env_file:
      - .env
    volumes:
      - ./rsmu_bot/static:/rsmu_bot/rsmu_bot/static
      - ./rsmu_bot/media:/rsmu_bot/rsmu_bot/media
    depends_on:
      - django
    command: python manage.py check_polls

volumes:
  db-data: