version: '3'

services:
  django:
    build: .
    env_file:
      - .env
    ports:
      - "8000:8000"
    command: [ "/rsmu_bot/docker/app.sh" ]
    volumes:
      - ./db.sqlite3:/rsmu_bot/db.sqlite3
      - ./rsmu_bot/static:/rsmu_bot/rsmu_bot/static
      - ./rsmu_bot/media:/rsmu_bot/rsmu_bot/media

  bot:
    build: .
    env_file:
      - .env
    volumes:
      - ./db.sqlite3:/rsmu_bot/db.sqlite3
      - ./rsmu_bot/static:/rsmu_bot/rsmu_bot/static
      - ./rsmu_bot/media:/rsmu_bot/rsmu_bot/media
    depends_on:
      - django
    command: python manage.py run_bot

