# Generated by Django 4.2.13 on 2024-07-23 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ElderMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400)),
                ('message', models.TextField(max_length=4000)),
                ('image', models.ImageField(blank=True, upload_to='eldermessage_img')),
                ('state', models.CharField(choices=[('A', 'Активно'), ('N', 'Неактивно')], max_length=1)),
            ],
            options={
                'verbose_name': 'Сообщение Онлайн Старосты',
            },
        ),
        migrations.CreateModel(
            name='ElderMessageButtons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400)),
                ('message', models.TextField(max_length=4000)),
                ('image', models.ImageField(blank=True, upload_to='eldermessagebuttons_img')),
                ('link', models.CharField(blank=True, max_length=400)),
                ('state', models.CharField(choices=[('A', 'Активно'), ('N', 'Неактивно')], max_length=1)),
                ('elder_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online_elder.eldermessage')),
            ],
            options={
                'verbose_name': 'Кнопки к сообщению онлайн старосты --- Темы',
            },
        ),
        migrations.CreateModel(
            name='SubElderMessageButtons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400)),
                ('message', models.TextField(max_length=4000)),
                ('image', models.ImageField(blank=True, upload_to='subeldermessagebuttons_img')),
                ('link', models.CharField(blank=True, max_length=400)),
                ('state', models.CharField(choices=[('A', 'Активно'), ('N', 'Неактивно')], max_length=1)),
                ('eldermessagebutton', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online_elder.eldermessagebuttons')),
            ],
            options={
                'verbose_name': 'Кнопки к Подтемам',
            },
        ),
    ]
