# Generated by Django 4.2.13 on 2024-07-10 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0005_rename_snils_botuser_auth_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PollsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='polls_images/')),
                ('file_size', models.IntegerField(blank=True, null=True)),
                ('width', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('color_mode', models.CharField(blank=True, max_length=20, null=True)),
                ('bit_depth', models.IntegerField(blank=True, null=True)),
                ('poll_number', models.IntegerField()),
                ('state', models.CharField(choices=[('uploaded', 'Uploaded'), ('in_processing', 'In Processing'), ('processed', 'Processed'), ('good', 'Good'), ('bad', 'Bad')], max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.botuser')),
            ],
            options={
                'verbose_name': 'Скрины опросников',
            },
        ),
    ]
