# Generated by Django 4.2.13 on 2024-07-07 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CurriculumsMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400)),
                ('message', models.TextField(max_length=4000)),
                ('image', models.ImageField(blank=True, upload_to='registration_img')),
                ('state', models.CharField(choices=[('A', 'Активно'), ('N', 'Неактивно')], max_length=1)),
            ],
            options={
                'verbose_name': 'Внеучебная деятельность',
            },
        ),
        migrations.CreateModel(
            name='MainMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400)),
                ('message', models.TextField(max_length=4000)),
                ('image', models.ImageField(blank=True, upload_to='registration_img')),
                ('state', models.CharField(choices=[('A', 'Активно'), ('N', 'Неактивно')], max_length=1)),
            ],
            options={
                'verbose_name': 'Главное сообщение',
            },
        ),
        migrations.CreateModel(
            name='RegistrationMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400)),
                ('message', models.TextField(max_length=4000)),
                ('image', models.ImageField(blank=True, upload_to='registration_img')),
                ('state', models.CharField(choices=[('A', 'Активно'), ('N', 'Неактивно')], max_length=1)),
            ],
            options={
                'verbose_name': 'Сообщение при регистрации',
            },
        ),
        migrations.CreateModel(
            name='UnknownMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400)),
                ('message', models.TextField(max_length=4000)),
                ('image', models.ImageField(blank=True, upload_to='registration_img')),
                ('state', models.CharField(choices=[('A', 'Активно'), ('N', 'Неактивно')], max_length=1)),
            ],
            options={
                'verbose_name': 'Сообщение если неизвестная команда',
            },
        ),
        migrations.CreateModel(
            name='WelcomeMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400)),
                ('message', models.TextField(max_length=4000)),
                ('image', models.ImageField(blank=True, upload_to='registration_img')),
                ('state', models.CharField(choices=[('A', 'Активно'), ('N', 'Неактивно')], max_length=1)),
            ],
            options={
                'verbose_name': 'Приветственное сообщение',
            },
        ),
    ]
