# Generated by Django 4.2.13 on 2024-07-07 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tg_messages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curriculumsmessage',
            name='image',
        ),
        migrations.CreateModel(
            name='CurriculumsButtons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400)),
                ('message', models.TextField(max_length=4000)),
                ('image', models.ImageField(blank=True, upload_to='curriculumsbuttons_img')),
                ('state', models.CharField(choices=[('A', 'Активно'), ('N', 'Неактивно')], max_length=1)),
                ('curriculums_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tg_messages.curriculumsmessage')),
            ],
            options={
                'verbose_name': 'Кнопки внеучебной деятельности',
            },
        ),
    ]
