# Generated by Django 4.2.13 on 2024-07-09 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg_messages', '0003_subcurriculumsbuttons_alter_unknownmessage_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcurriculumsbuttons',
            name='link',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AlterField(
            model_name='subsubcurriculumsbuttons',
            name='link',
            field=models.CharField(blank=True, max_length=400),
        ),
    ]
